//! Generates Rust constants from the codepoint lists in `resources/`.
//!
//! Each `resources/<name>.txt` file holds one hexadecimal codepoint per line —
//! blank lines and anything after a `#` are ignored — and becomes a
//! `pub const <NAME>: &[u32]` in `$OUT_DIR/codepoints.rs`, which `src/lib.rs`
//! pulls in with `include!`. Naming follows the file: `cjk-basic.txt` gives
//! `CJK_BASIC`. Dropping a new list into `resources/` is all it takes to get a
//! constant; there is nothing to register here.
//!
//! The input is curated by hand, so mistakes have to be loud: a line that is not
//! a codepoint stops the build rather than quietly shrinking the font.

use std::collections::HashSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// How many codepoints to put on a line of the generated file.
const PER_LINE: usize = 12;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let resources = manifest_dir.join("resources");

    println!("cargo:rerun-if-changed=build.rs");
    // Enough to catch added, removed and edited lists.
    println!("cargo:rerun-if-changed={}", resources.display());

    let mut lists = Vec::new();
    for entry in fs::read_dir(&resources).expect("resources directory") {
        let path = entry.expect("directory entry").path();
        if path.extension().and_then(|extension| extension.to_str()) == Some("txt") {
            lists.push(path);
        }
    }
    lists.sort();

    let mut generated = String::from(
        "// Generated by build.rs from the lists in resources/. Do not edit.\n\
         //\n\
         // Each constant holds the codepoints from the file of the same name, in\n\
         // file order, with duplicates dropped.\n\n",
    );

    if lists.is_empty() {
        println!("cargo:warning=no codepoint lists found in {}", resources.display());
    }

    for path in &lists {
        let stem = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("list file name");
        let (codepoints, duplicates) = read_list(path);
        if codepoints.is_empty() {
            println!("cargo:warning={} has no codepoints in it", path.display());
        }
        write_constant(&mut generated, stem, &codepoints, duplicates);
    }

    fs::write(out_dir.join("codepoints.rs"), generated).expect("write codepoints.rs");
}

/// Reads one hexadecimal codepoint per line.
///
/// Returns the codepoints in file order along with how many duplicate entries
/// were dropped.
fn read_list(path: &Path) -> (Vec<u32>, usize) {
    let text = fs::read_to_string(path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));

    let mut seen = HashSet::new();
    let mut codepoints = Vec::new();
    let mut duplicates = 0;

    for (index, line) in text.lines().enumerate() {
        let line = line.split('#').next().unwrap_or_default().trim();
        if line.is_empty() {
            continue;
        }
        let where_ = format!("{}:{}", path.display(), index + 1);
        let digits = line
            .strip_prefix("0x")
            .or_else(|| line.strip_prefix("0X"))
            .or_else(|| line.strip_prefix("U+"))
            .or_else(|| line.strip_prefix("u+"))
            .unwrap_or(line);
        let codepoint = u32::from_str_radix(digits, 16)
            .unwrap_or_else(|_| panic!("{where_}: {line:?} is not a hexadecimal codepoint"));
        assert!(
            codepoint <= 0x10FFFF,
            "{where_}: U+{codepoint:04X} is beyond the Unicode range"
        );
        if (0xD800..=0xDFFF).contains(&codepoint) {
            // `char::from_u32` refuses surrogates, so the font would silently
            // not get this glyph.
            println!("cargo:warning={where_}: U+{codepoint:04X} is a surrogate and cannot be used");
        }
        if seen.insert(codepoint) {
            codepoints.push(codepoint);
        } else {
            duplicates += 1;
        }
    }

    (codepoints, duplicates)
}

/// Writes one `pub const` for a list.
fn write_constant(out: &mut String, stem: &str, codepoints: &[u32], duplicates: usize) {
    let _ = writeln!(
        out,
        "/// Codepoints from `resources/{stem}.txt`: {} in total.",
        codepoints.len()
    );
    if duplicates > 0 {
        let _ = writeln!(
            out,
            "///\n/// {duplicates} duplicate {} dropped.",
            if duplicates == 1 { "entry was" } else { "entries were" }
        );
    }
    let _ = writeln!(out, "pub const {}: &[u32] = &[", constant_name(stem));
    for chunk in codepoints.chunks(PER_LINE) {
        let values = chunk
            .iter()
            .map(|codepoint| format!("0x{codepoint:04x}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    {values},");
    }
    out.push_str("];\n\n");
}

/// `cjk-basic` becomes `CJK_BASIC`.
fn constant_name(stem: &str) -> String {
    let mut name = String::with_capacity(stem.len());
    for character in stem.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_uppercase());
        } else {
            name.push('_');
        }
    }
    if name.starts_with(|character: char| character.is_ascii_digit()) {
        name.insert(0, '_');
    }
    name
}
