//! A fake font library for testing and development purposes.
//!
//! Provides a `FakeFont` type that can be used to generate fonts with specific scripts and axes for testing purposes.
#![deny(missing_docs)]
use babelfont::{BabelfontError, DesignCoord, Font, FormatSpecific, Tag, UserCoord};
use flate2::read::GzDecoder;
use fontmerge::{GlyphsetFilter, fontsubset};
use google_fonts_glyphsets::{
    GF_ARABIC_CORE, GF_ARABIC_KERNEL, GF_CYRILLIC_CORE, GF_GREEK_CORE, GF_LATIN_AFRICAN,
    GF_LATIN_CORE, GF_LATIN_KERNEL, GF_LATIN_PLUS, GF_LATIN_VIETNAMESE,
};

use std::collections::{HashMap, HashSet};
use std::io::Read;
use std::sync::LazyLock;
mod fakeaxis;
mod key;

pub use key::{AxisSpec, KEY_VERSION, KeyError, Options};

/// Codepoint lists for the scripts that Google Fonts publishes no glyphset for.
///
/// Generated by `build.rs` from the one-hex-codepoint-per-line files in
/// `resources/`.
pub mod codepoints {
    include!(concat!(env!("OUT_DIR"), "/codepoints.rs"));
}

fn unzip_and_babelfont(bytes: &[u8]) -> Font {
    let mut d = GzDecoder::new(bytes);
    let mut s = String::new();
    d.read_to_string(&mut s).unwrap();
    serde_json::from_str(&s).unwrap()
}

static A_BIG_FONT: LazyLock<Font> =
    LazyLock::new(|| unzip_and_babelfont(include_bytes!("../resources/everything.babelfont.gz")));

/// Represents the coverage level of Latin characters in a fake font.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LatinCoverage {
    /// Full Latin coverage, including core, kernel, African, Vietnamese, and additional Latin characters.
    Full,
    /// Google Fonts' expected core Latin coverage, including only the essential Latin characters and diacritic combinations.
    Core,
    /// Kernel Latin coverage, including the minimal set of Latin characters.
    Kernel,
}

impl LatinCoverage {
    /// The name the web page's coverage tiles use, and the one a key writes.
    pub fn name(&self) -> &'static str {
        match self {
            LatinCoverage::Full => "full",
            LatinCoverage::Core => "core",
            LatinCoverage::Kernel => "kernel",
        }
    }

    /// Reads one of those names back.
    pub fn from_name(name: &str) -> Result<Self, String> {
        Ok(match name {
            "full" => LatinCoverage::Full,
            "core" => LatinCoverage::Core,
            "kernel" => LatinCoverage::Kernel,
            other => {
                return Err(format!(
                    "unknown Latin coverage {other:?}: expected \"full\", \"core\" or \"kernel\""
                ));
            }
        })
    }
}

/// Represents other script subsets that can be included in a fake font.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OtherSubsets {
    /// Greek script subset.
    Greek,
    /// Cyrillic script subset.
    Cyrillic,
    /// Basic CJK (Chinese, Japanese, Korean) script subset.
    CjkBasic,
    /// Devanagari script subset.
    Devanagari,
    /// Bengali script subset.
    Bengali,
    /// Standard Arabic script subset.
    StandardArabic,
    /// Urdu and Farsi script subset.
    UrduFarsi,
    /// Thai script subset.
    Thai,
    /// Tamil script subset.
    Tamil,
    /// Telugu script subset.
    Telugu,
    /// Kannada script subset.
    Kannada,
    /// Malayalam script subset.
    Malayalam,
    /// Gujarati script subset.
    Gujarati,
    /// Gurmukhi script subset.
    Gurmukhi,
    /// Oriya, also called Odia, script subset.
    Oriya,
    /// Khmer script subset.
    Khmer,
    /// Lao script subset.
    Lao,
    /// Myanmar, also called Burmese, script subset.
    Myanmar,
    /// Ethiopic script subset.
    Ethiopic,
    /// Armenian script subset.
    Armenian,
    /// Georgian script subset.
    Georgian,
}

/// Every subset, with the name its tile on the page uses.
///
/// One list, because the page's `value` attributes, [`OtherSubsets::from_name`]
/// and the keys a size cache is built from all have to agree character for
/// character.
const SUBSET_NAMES: [(OtherSubsets, &'static str); 21] = [
    (OtherSubsets::Greek, "greek"),
    (OtherSubsets::Cyrillic, "cyrillic"),
    (OtherSubsets::CjkBasic, "cjk-basic"),
    (OtherSubsets::Devanagari, "devanagari"),
    (OtherSubsets::Bengali, "bengali"),
    (OtherSubsets::StandardArabic, "standard-arabic"),
    (OtherSubsets::UrduFarsi, "farsi-urdu"),
    (OtherSubsets::Thai, "thai"),
    (OtherSubsets::Tamil, "tamil"),
    (OtherSubsets::Telugu, "telugu"),
    (OtherSubsets::Kannada, "kannada"),
    (OtherSubsets::Malayalam, "malayalam"),
    (OtherSubsets::Gujarati, "gujarati"),
    (OtherSubsets::Gurmukhi, "gurmukhi"),
    (OtherSubsets::Oriya, "oriya"),
    (OtherSubsets::Khmer, "khmer"),
    (OtherSubsets::Lao, "lao"),
    (OtherSubsets::Myanmar, "myanmar"),
    (OtherSubsets::Ethiopic, "ethiopic"),
    (OtherSubsets::Armenian, "armenian"),
    (OtherSubsets::Georgian, "georgian"),
];

impl OtherSubsets {
    /// The name the web page's script tiles use, and the one a key writes.
    pub fn name(&self) -> &'static str {
        SUBSET_NAMES
            .iter()
            .find(|(subset, _)| subset == self)
            .map(|(_, name)| *name)
            .expect("every subset has a name")
    }

    /// Reads one of those names back.
    pub fn from_name(name: &str) -> Result<Self, String> {
        SUBSET_NAMES
            .iter()
            .find(|(_, known)| *known == name)
            .map(|(subset, _)| *subset)
            .ok_or_else(|| {
                let expected = SUBSET_NAMES
                    .iter()
                    .map(|(_, name)| *name)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("unknown script {name:?}: expected one of {expected}")
            })
    }
}

/// The main type representing a fake font.
pub struct FakeFont(Font);

impl FakeFont {
    /// Creates a new fake font with the specified Latin coverage and optional Greek and Cyrillic scripts.
    pub fn new(
        latin_coverage: LatinCoverage,
        other_subsets: &[OtherSubsets],
    ) -> Result<Self, fontmerge::FontmergeError> {
        let mut wanted_cps = HashSet::new();

        match latin_coverage {
            LatinCoverage::Core => {
                wanted_cps.extend(GF_LATIN_CORE.iter_codepoints().collect::<Vec<u32>>())
            }
            LatinCoverage::Kernel => {
                wanted_cps.extend(GF_LATIN_KERNEL.iter_codepoints().collect::<Vec<u32>>())
            }
            LatinCoverage::Full => {
                wanted_cps.extend(GF_LATIN_CORE.iter_codepoints().collect::<Vec<u32>>());
                wanted_cps.extend(GF_LATIN_KERNEL.iter_codepoints().collect::<Vec<u32>>());
                wanted_cps.extend(GF_LATIN_AFRICAN.iter_codepoints().collect::<Vec<u32>>());
                wanted_cps.extend(GF_LATIN_VIETNAMESE.iter_codepoints().collect::<Vec<u32>>());
                wanted_cps.extend(GF_LATIN_PLUS.iter_codepoints().collect::<Vec<u32>>());
            }
        };
        for subset in other_subsets {
            match subset {
                OtherSubsets::Greek => {
                    wanted_cps.extend(GF_GREEK_CORE.iter_codepoints().collect::<Vec<u32>>());
                }
                OtherSubsets::Cyrillic => {
                    wanted_cps.extend(GF_CYRILLIC_CORE.iter_codepoints().collect::<Vec<u32>>());
                }
                OtherSubsets::CjkBasic => {
                    wanted_cps.extend(codepoints::CJK_BASIC.iter().copied());
                }
                OtherSubsets::Devanagari => {
                    wanted_cps.extend(codepoints::DEVANAGARI.iter().copied());
                }
                OtherSubsets::Bengali => {
                    wanted_cps.extend(codepoints::BENGALI.iter().copied());
                }
                OtherSubsets::StandardArabic => {
                    wanted_cps.extend(GF_ARABIC_KERNEL.iter_codepoints().collect::<Vec<u32>>());
                }
                OtherSubsets::UrduFarsi => {
                    wanted_cps.extend(GF_ARABIC_KERNEL.iter_codepoints().collect::<Vec<u32>>());
                    wanted_cps.extend(GF_ARABIC_CORE.iter_codepoints().collect::<Vec<u32>>());
                }
                OtherSubsets::Thai => {
                    wanted_cps.extend(codepoints::THAI.iter().copied());
                }
                OtherSubsets::Tamil => {
                    wanted_cps.extend(codepoints::TAMIL.iter().copied());
                }
                OtherSubsets::Telugu => {
                    wanted_cps.extend(codepoints::TELUGU.iter().copied());
                }
                OtherSubsets::Kannada => {
                    wanted_cps.extend(codepoints::KANNADA.iter().copied());
                }
                OtherSubsets::Malayalam => {
                    wanted_cps.extend(codepoints::MALAYALAM.iter().copied());
                }
                OtherSubsets::Gujarati => {
                    wanted_cps.extend(codepoints::GUJARATI.iter().copied());
                }
                OtherSubsets::Gurmukhi => {
                    wanted_cps.extend(codepoints::GURMUKHI.iter().copied());
                }
                OtherSubsets::Oriya => {
                    wanted_cps.extend(codepoints::ORIYA.iter().copied());
                }
                OtherSubsets::Khmer => {
                    wanted_cps.extend(codepoints::KHMER.iter().copied());
                }
                OtherSubsets::Lao => {
                    wanted_cps.extend(codepoints::LAO.iter().copied());
                }
                OtherSubsets::Myanmar => {
                    wanted_cps.extend(codepoints::MYANMAR.iter().copied());
                }
                OtherSubsets::Ethiopic => {
                    wanted_cps.extend(codepoints::ETHIOPIC.iter().copied());
                }
                OtherSubsets::Armenian => {
                    wanted_cps.extend(codepoints::ARMENIAN.iter().copied());
                }
                OtherSubsets::Georgian => {
                    wanted_cps.extend(codepoints::GEORGIAN.iter().copied());
                }
            }
        }
        let wanted_chars = wanted_cps
            .into_iter()
            .filter_map(std::char::from_u32)
            .collect::<Vec<char>>();

        Ok(FakeFont(fontsubset(
            A_BIG_FONT.clone(),
            GlyphsetFilter::new_from_codepoints(
                wanted_chars,
                &mut Font::default(),
                &A_BIG_FONT,
                fontmerge::ExistingGlyphHandling::Skip,
            ),
            fontmerge::LayoutHandling::Closure,
            false,
            true,
        )?))
    }

    /// Adds an axis to the fake font with the specified tag, name, low, high, default values, and flags indicating whether it affects metrics and kerning.
    #[allow(clippy::too_many_arguments)]
    pub fn add_axis(
        &mut self,
        tag: &str,
        name: &str,
        low: f64,
        high: f64,
        default: f64,
        affects_metrics: bool,
        affects_kerning: bool,
    ) {
        let fourbyte_tag = &format!("{: <4}", tag)[0..4];
        let mut fs = FormatSpecific::default();
        fs.insert(
            "affects_metrics".to_string(),
            serde_json::Value::Bool(affects_metrics),
        );
        fs.insert(
            "affects_kerning".to_string(),
            serde_json::Value::Bool(affects_kerning),
        );
        let mut map = if tag == "wght" {
            fakeaxis::weight_warping_map(low, default, high)
        } else {
            vec![
                (UserCoord::new(low), DesignCoord::new(low)),
                (UserCoord::new(default), DesignCoord::new(default)),
                (UserCoord::new(high), DesignCoord::new(high)),
            ]
        };
        map.dedup_by_key(|(user, _design)| user.to_f64());
        self.0.axes.push(babelfont::Axis {
            name: name.into(),
            tag: Tag::new_checked(fourbyte_tag.as_bytes()).unwrap(),
            min: Some(UserCoord::new(low)),
            max: Some(UserCoord::new(high)),
            default: Some(UserCoord::new(default)),
            map: Some(map),
            format_specific: fs,
            ..Default::default()
        })
    }

    /// Compiles the fake font into a binary font file, returning the resulting bytes or an error.
    pub fn compile(self) -> Result<Vec<u8>, BabelfontError> {
        use babelfont::convertors::fontir::CompilationOptions;

        let bytes = babelfont::convertors::fontir::BabelfontIrSource::compile(
            self.0,
            CompilationOptions::default(),
        )?;
        Ok(bytes)
    }
}

/// Rejects a tag or a coordinate range that [`FakeFont::add_axis`] cannot turn
/// into an axis.
///
/// `add_axis` pads the tag to four bytes and unwraps it, so a tag that is not
/// exactly four printable ASCII bytes panics, which in wasm takes the module
/// down with it. Callers which accept axis descriptions from a person — the
/// page, or [`Options::from_key`] — reject them with this first.
pub fn check_axis(tag: &str, low: f64, high: f64, default: f64) -> Result<(), String> {
    let bytes = tag.as_bytes();
    if bytes.len() != 4 || !bytes.iter().all(|byte| (0x20..=0x7e).contains(byte)) {
        return Err(format!(
            "axis tag {tag:?} must be exactly four printable ASCII characters"
        ));
    }
    if ![low, high, default].iter().all(|value| value.is_finite()) {
        return Err(format!(
            "axis {tag:?} has a coordinate that is not a finite number"
        ));
    }
    if low >= high {
        return Err(format!("axis {tag:?} needs low to be less than high"));
    }
    if default < low || default > high {
        return Err(format!(
            "axis {tag:?} needs its default to lie between low and high"
        ));
    }
    Ok(())
}

/// Returns a map of table tags to their lengths for the given font bytes.
pub fn table_stats(font: &[u8]) -> Result<HashMap<String, usize>, String> {
    let font_ref = skrifa::FontRef::new(font).map_err(|e| e.to_string())?;
    let mut stats = HashMap::new();
    for table in font_ref.table_directory().table_records() {
        stats.insert(table.tag().to_string(), table.length() as usize);
    }
    Ok(stats)
}

#[cfg(test)]
mod tests {
    use babelfont::SmolStr;

    use super::*;

    #[test]
    fn test_basic() {
        let font_all = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        assert_eq!(font_all.0.masters.len(), 1);
        assert_eq!(font_all.0.axes.len(), 0);
        assert_eq!(font_all.0.glyphs.iter().count(), 1158);

        let font_core = FakeFont::new(LatinCoverage::Core, &[]).unwrap();
        assert_eq!(font_core.0.masters.len(), 1);
        assert_eq!(font_core.0.glyphs.iter().count(), 623);

        let font_core = FakeFont::new(LatinCoverage::Core, &[OtherSubsets::Greek]).unwrap();
        assert_eq!(font_core.0.masters.len(), 1);
        assert_eq!(font_core.0.glyphs.iter().count(), 772);
    }

    #[test]
    fn test_masters() {
        let mut font_core = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 400.0, 400.0, true, true);
        font_core.fill_out_masters(false, false);
        assert_eq!(font_core.0.axes.len(), 1);
        assert_eq!(font_core.0.masters.len(), 2);

        let mut font_core = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 700.0, 400.0, true, true);
        font_core.fill_out_masters(false, false);
        assert_eq!(font_core.0.axes.len(), 1);
        assert_eq!(font_core.0.masters.len(), 3);

        // Add weight and width
        let mut font_core = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 400.0, 700.0, true, true);
        font_core.add_axis("wdth", "Width", 75.0, 100.0, 100.0, true, true);
        font_core.fill_out_masters(false, false);
        assert_eq!(font_core.0.axes.len(), 2);
        assert_eq!(font_core.0.masters.len(), 6);

        let mut font_core = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 400.0, 700.0, true, true);
        font_core.add_axis("wdth", "Width", 75.0, 100.0, 125.0, true, true);
        font_core.fill_out_masters(true, true);
        assert_eq!(font_core.0.axes.len(), 2);
        assert_eq!(font_core.0.masters.len(), 9);
    }

    #[test]
    fn test_add_deva_and_compile() {
        let mut font_core =
            FakeFont::new(LatinCoverage::Full, &[OtherSubsets::Devanagari]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 700.0, 400.0, true, true);
        font_core.fill_out_masters(false, false);
        font_core.compile().expect("Compilation failed");

        // and arabic
        let mut font_core =
            FakeFont::new(LatinCoverage::Full, &[OtherSubsets::StandardArabic]).unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 700.0, 400.0, true, true);
        font_core.fill_out_masters(false, false);
        font_core.compile().expect("Compilation failed");

        // and both
        let mut font_core = FakeFont::new(
            LatinCoverage::Full,
            &[OtherSubsets::Devanagari, OtherSubsets::StandardArabic],
        )
        .unwrap();
        font_core.add_axis("wght", "Weight", 100.0, 700.0, 400.0, true, true);
        font_core.fill_out_masters(false, false);
        font_core.compile().expect("Compilation failed");
    }

    #[test]
    fn test_arbitrary_axis() {
        let mut font_core = FakeFont::new(LatinCoverage::Full, &[]).unwrap();
        font_core.add_axis("slnt", "Slant", 0.0, 10.0, 0.0, true, true);
        font_core.fill_out_masters(false, false);
        assert_eq!(font_core.0.axes.len(), 1);
        assert_eq!(font_core.0.masters.len(), 2);
        println!("Map: {:?}", font_core.0.axes[0].map);
        font_core.compile().expect("Compilation failed");
    }

    /// Combining scripts must stay unambiguous, whatever the order they are
    /// merged in: no codepoint may end up on two glyphs (the cmap would be
    /// ambiguous) and no two glyphs may share a name (references would be). A
    /// script variant that shares a codepoint with a Latin glyph is kept, but
    /// loses the codepoint.
    #[test]
    fn merged_fonts_stay_unambiguous() {
        let font = FakeFont::new(
            LatinCoverage::Full,
            &[
                OtherSubsets::Devanagari,
                // OtherSubsets::Tamil,
                // OtherSubsets::Telugu,
                // OtherSubsets::Kannada,
                OtherSubsets::StandardArabic,
                OtherSubsets::UrduFarsi,
            ],
        )
        .unwrap();

        let mut by_codepoint: HashMap<u32, SmolStr> = HashMap::new();
        let mut by_name: HashSet<SmolStr> = HashSet::new();
        for glyph in font.0.glyphs.iter() {
            assert!(
                by_name.insert(glyph.name.clone()),
                "duplicate glyph name {}",
                glyph.name
            );
            for codepoint in glyph.codepoints.iter() {
                if let Some(other) = by_codepoint.insert(*codepoint, glyph.name.clone()) {
                    panic!("U+{codepoint:04X} is on both {other} and {}", glyph.name);
                }
            }
        }
    }

    #[test]
    fn combinations_compile() {
        let mut one = FakeFont::new(LatinCoverage::Full, &[OtherSubsets::Tamil]).unwrap();
        one.fill_out_masters(false, false);
        let bytes = one.compile().expect("compile");
        assert!(!bytes.is_empty(), "compiled font should have non-zero size");

        let one = FakeFont::new(
            LatinCoverage::Full,
            &[OtherSubsets::Devanagari, OtherSubsets::Tamil],
        )
        .unwrap();
        let bytes = one.compile().expect("compile");
        assert!(!bytes.is_empty(), "compiled font should have non-zero size");
    }

    /// The names are the page's tile values, and the key format writes the same
    /// ones, so this list is what keeps the page, the keys and the library in
    /// step.
    #[test]
    fn names_match_the_page() {
        for name in [
            "greek",
            "cyrillic",
            "cjk-basic",
            "devanagari",
            "bengali",
            "standard-arabic",
            "farsi-urdu",
            "thai",
            "tamil",
            "telugu",
            "kannada",
            "malayalam",
            "gujarati",
            "gurmukhi",
            "oriya",
            "khmer",
            "lao",
            "myanmar",
            "ethiopic",
            "armenian",
            "georgian",
        ] {
            let subset = OtherSubsets::from_name(name).expect(name);
            assert_eq!(subset.name(), name, "{name} did not round trip");
        }
        for wrong in ["", "Greek", "farsi", "cjkbasic", "arabic", "devanagari "] {
            assert!(
                OtherSubsets::from_name(wrong).is_err(),
                "{wrong:?} should not parse"
            );
        }

        for (name, coverage) in [
            ("full", LatinCoverage::Full),
            ("core", LatinCoverage::Core),
            ("kernel", LatinCoverage::Kernel),
        ] {
            assert_eq!(LatinCoverage::from_name(name).expect(name), coverage);
            assert_eq!(coverage.name(), name);
        }
        assert!(LatinCoverage::from_name("Core").is_err());
        assert!(LatinCoverage::from_name("").is_err());
    }

    /// `add_axis` panics on a tag it cannot use, so anything taking axes from a
    /// person checks them with this first.
    #[test]
    fn check_axis_accepts_what_add_axis_can_use() {
        assert!(check_axis("slnt", -15.0, 15.0, 0.0).is_ok());
        assert!(check_axis("opsz", 6.0, 144.0, 12.0).is_ok());
        // A default sitting on either end of the range is fine.
        assert!(check_axis("XXXX", 0.0, 100.0, 0.0).is_ok());
        assert!(check_axis("XXXX", 0.0, 100.0, 100.0).is_ok());
        // Spaces are printable ASCII, so a padded tag is legal.
        assert!(check_axis("ab  ", 0.0, 100.0, 0.0).is_ok());

        // Too short / too long / not printable ASCII / not ASCII at all.
        assert!(check_axis("abc", 0.0, 10.0, 5.0).is_err());
        assert!(check_axis("abcde", 0.0, 10.0, 5.0).is_err());
        assert!(check_axis("ab\tc", 0.0, 10.0, 5.0).is_err());
        assert!(check_axis("ab\u{e7}d", 0.0, 10.0, 5.0).is_err());
        assert!(check_axis("", 0.0, 10.0, 5.0).is_err());
        // Numeric problems.
        assert!(check_axis("slnt", 15.0, -15.0, 0.0).is_err());
        assert!(check_axis("slnt", 0.0, 0.0, 0.0).is_err());
        assert!(check_axis("slnt", 0.0, 10.0, 11.0).is_err());
        assert!(check_axis("slnt", 0.0, 10.0, f64::NAN).is_err());
        assert!(check_axis("slnt", f64::NEG_INFINITY, 10.0, 0.0).is_err());
    }
}
