name: Build GH Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build web site
        run: |
          wasm-pack build fakefont-web --target web --out-dir ../web/pkg
      - name: Upload
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: web
  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
